#' calc_prelim_stats: Calculates initial statistics for a Seurat object
#' as required for downstream analysis
#'
#' @description Calculates the percentage of mitochondrial and ribosomal
#' reads for each cell in the Seurat object. These statistics can be used for
#' filtering or for feature regression in downstream normalization.
#'
#' @param so A Seurat object imported from .h5 file generated by 10X
#' CellRanger
#' @param sampleID An optional character argument to include sample label (useful
#' for downstream multi-sample analysis)
#'
#' @return A Seurat object with calculated statistics added as metadata
#'
#' @export
calc_prelim_stats <- function(so, sampleID = NULL) {
  if (!is.null(sampleID)) {
    so$Sample <- sampleID
  }
  so[["percent.mt"]] <- Seurat::PercentageFeatureSet(so, pattern = "^MT-|^mt-")
  so[["percent.RP"]] <- Seurat::PercentageFeatureSet(
    so,
    pattern = "^R[PL,pl]|R[PS,ps]"
  )

  return(so)
}
